version: '3.9'
services:
  application:
    container_name: blog-engine
    image: ghcr.io/eybv/blog-engine:v1.0.1
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - CATALINA_OPTS=-DJDBC_DATABASE_URL="jdbc:postgresql://database:5432/blog?user=blog-engine&password=pswd"
      - TZ=Europe/Moscow
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: database
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=blog-engine
      - POSTGRES_PASSWORD=pswd
      - TZ=Europe/Moscow
    volumes:
      - ./configuration/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
