### MANUAL TEST
### SEE CODE IN SERVER LOG
### one per attempt, lifetime 5 minutes

POST https://localhost:8443/user/password/reset
Content-Type: application/json

{
  "username": "test-user-account"
}

> {%
client.test("Should respond No Content", function () {
    client.assert(response.status === 204, "Response status isn't 204")
})
%}

###

POST https://localhost:8443/user/password/reset/confirm
Content-Type: application/json

{
  "username": "test-user-account",
  "code": "42975c8b-3cc7-4707-86d3-02c10ce70e3b",
  "password": "test-password"
}

> {%
client.test("When correct code -> Should return user with token", function () {
    client.assert(response.status === 200, "Response status isn't 200")
    client.assert(response.body.id !== null, "User ID isn't present")
    client.assert(response.body.username !== null, "Username isn't present")
    client.assert(response.body.roles.length > 0, "Roles isn't present")
    client.assert(response.body.token !== null, "Token isn't present")
})
%}
