name: Publish to GitHub Packages

on:
  release:
    types:  [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GHCR_REGISTRY: ghcr.io
      IMAGE: eybv/blog-engine

    steps:
      - uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.GHCR_REGISTRY }}
          repository: ${{ env.IMAGE }}
          tag_with_ref: true
